apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: trainer
  template:
    metadata:
      labels:
        component: trainer
    spec:
      containers:
      - name: trainer
        image: balbains2/pokecentre-trainers
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PG_USER
            value: postgres
          - name: PG_HOST
            value: postgress-cluster-ip-service
          - name: PG_PORT
            value: "5432"
          - name: PG_DATABASE
            value: pokecentre
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: trainer-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: trainer
  ports:
  - port: 5001
    targetPort: 5001
