// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.2
// source: pokemon.proto

package pokemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionGroupDetails []*VersionGroupDetails `protobuf:"bytes,2,rep,name=versionGroupDetails,proto3" json:"versionGroupDetails,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Move) GetVersionGroupDetails() []*VersionGroupDetails {
	if x != nil {
		return x.VersionGroupDetails
	}
	return nil
}

type VersionGroupDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionName     string `protobuf:"bytes,1,opt,name=versionName,proto3" json:"versionName,omitempty"`
	MoveLearnMethod string `protobuf:"bytes,2,opt,name=moveLearnMethod,proto3" json:"moveLearnMethod,omitempty"`
	LevelLearnedAt  int32  `protobuf:"varint,3,opt,name=levelLearnedAt,proto3" json:"levelLearnedAt,omitempty"`
}

func (x *VersionGroupDetails) Reset() {
	*x = VersionGroupDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionGroupDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionGroupDetails) ProtoMessage() {}

func (x *VersionGroupDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionGroupDetails.ProtoReflect.Descriptor instead.
func (*VersionGroupDetails) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *VersionGroupDetails) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *VersionGroupDetails) GetMoveLearnMethod() string {
	if x != nil {
		return x.MoveLearnMethod
	}
	return ""
}

func (x *VersionGroupDetails) GetLevelLearnedAt() int32 {
	if x != nil {
		return x.LevelLearnedAt
	}
	return 0
}

type Ability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slot     int32  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	IsHidden bool   `protobuf:"varint,3,opt,name=isHidden,proto3" json:"isHidden,omitempty"`
}

func (x *Ability) Reset() {
	*x = Ability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *Ability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ability) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Ability) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

type Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Effort   int32  `protobuf:"varint,2,opt,name=effort,proto3" json:"effort,omitempty"`
	BaseStat int32  `protobuf:"varint,3,opt,name=baseStat,proto3" json:"baseStat,omitempty"`
}

func (x *Stat) Reset() {
	*x = Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{3}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetEffort() int32 {
	if x != nil {
		return x.Effort
	}
	return 0
}

func (x *Stat) GetBaseStat() int32 {
	if x != nil {
		return x.BaseStat
	}
	return 0
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slot int32  `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{4}
}

func (x *Type) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type Sprite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrontDefault     string `protobuf:"bytes,1,opt,name=frontDefault,proto3" json:"frontDefault,omitempty"`
	BackDefault      string `protobuf:"bytes,2,opt,name=backDefault,proto3" json:"backDefault,omitempty"`
	FrontShiny       string `protobuf:"bytes,3,opt,name=frontShiny,proto3" json:"frontShiny,omitempty"`
	BackShiny        string `protobuf:"bytes,4,opt,name=backShiny,proto3" json:"backShiny,omitempty"`
	FrontFemale      string `protobuf:"bytes,5,opt,name=frontFemale,proto3" json:"frontFemale,omitempty"`
	BackFemale       string `protobuf:"bytes,6,opt,name=backFemale,proto3" json:"backFemale,omitempty"`
	BackShinyFemale  string `protobuf:"bytes,7,opt,name=backShinyFemale,proto3" json:"backShinyFemale,omitempty"`
	FrontShinyFemale string `protobuf:"bytes,8,opt,name=frontShinyFemale,proto3" json:"frontShinyFemale,omitempty"`
}

func (x *Sprite) Reset() {
	*x = Sprite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sprite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sprite) ProtoMessage() {}

func (x *Sprite) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sprite.ProtoReflect.Descriptor instead.
func (*Sprite) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{5}
}

func (x *Sprite) GetFrontDefault() string {
	if x != nil {
		return x.FrontDefault
	}
	return ""
}

func (x *Sprite) GetBackDefault() string {
	if x != nil {
		return x.BackDefault
	}
	return ""
}

func (x *Sprite) GetFrontShiny() string {
	if x != nil {
		return x.FrontShiny
	}
	return ""
}

func (x *Sprite) GetBackShiny() string {
	if x != nil {
		return x.BackShiny
	}
	return ""
}

func (x *Sprite) GetFrontFemale() string {
	if x != nil {
		return x.FrontFemale
	}
	return ""
}

func (x *Sprite) GetBackFemale() string {
	if x != nil {
		return x.BackFemale
	}
	return ""
}

func (x *Sprite) GetBackShinyFemale() string {
	if x != nil {
		return x.BackShinyFemale
	}
	return ""
}

func (x *Sprite) GetFrontShinyFemale() string {
	if x != nil {
		return x.FrontShinyFemale
	}
	return ""
}

type Colour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Colour) Reset() {
	*x = Colour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Colour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Colour) ProtoMessage() {}

func (x *Colour) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Colour.ProtoReflect.Descriptor instead.
func (*Colour) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{6}
}

func (x *Colour) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Colour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EggGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EggGroup) Reset() {
	*x = EggGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EggGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EggGroup) ProtoMessage() {}

func (x *EggGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EggGroup.ProtoReflect.Descriptor instead.
func (*EggGroup) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{7}
}

func (x *EggGroup) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EggGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EvolvesFromSpecies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EvolvesFromSpecies) Reset() {
	*x = EvolvesFromSpecies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvolvesFromSpecies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolvesFromSpecies) ProtoMessage() {}

func (x *EvolvesFromSpecies) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolvesFromSpecies.ProtoReflect.Descriptor instead.
func (*EvolvesFromSpecies) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{8}
}

func (x *EvolvesFromSpecies) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EvolvesFromSpecies) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Shape struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Shape) Reset() {
	*x = Shape{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shape) ProtoMessage() {}

func (x *Shape) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shape.ProtoReflect.Descriptor instead.
func (*Shape) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{9}
}

func (x *Shape) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shape) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Species struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseHappiness      int32               `protobuf:"varint,1,opt,name=baseHappiness,proto3" json:"baseHappiness,omitempty"`
	CaptureRate        int32               `protobuf:"varint,2,opt,name=captureRate,proto3" json:"captureRate,omitempty"`
	Color              *Colour             `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	EggGroups          []*EggGroup         `protobuf:"bytes,4,rep,name=eggGroups,proto3" json:"eggGroups,omitempty"`
	EvolutionChainId   int32               `protobuf:"varint,5,opt,name=evolutionChainId,proto3" json:"evolutionChainId,omitempty"`
	EvolvesFromSpecies *EvolvesFromSpecies `protobuf:"bytes,6,opt,name=evolvesFromSpecies,proto3" json:"evolvesFromSpecies,omitempty"`
	FlavorText         string              `protobuf:"bytes,7,opt,name=flavorText,proto3" json:"flavorText,omitempty"`
	Genus              string              `protobuf:"bytes,8,opt,name=genus,proto3" json:"genus,omitempty"`
	Shape              *Shape              `protobuf:"bytes,9,opt,name=shape,proto3" json:"shape,omitempty"`
}

func (x *Species) Reset() {
	*x = Species{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Species) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Species) ProtoMessage() {}

func (x *Species) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Species.ProtoReflect.Descriptor instead.
func (*Species) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{10}
}

func (x *Species) GetBaseHappiness() int32 {
	if x != nil {
		return x.BaseHappiness
	}
	return 0
}

func (x *Species) GetCaptureRate() int32 {
	if x != nil {
		return x.CaptureRate
	}
	return 0
}

func (x *Species) GetColor() *Colour {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Species) GetEggGroups() []*EggGroup {
	if x != nil {
		return x.EggGroups
	}
	return nil
}

func (x *Species) GetEvolutionChainId() int32 {
	if x != nil {
		return x.EvolutionChainId
	}
	return 0
}

func (x *Species) GetEvolvesFromSpecies() *EvolvesFromSpecies {
	if x != nil {
		return x.EvolvesFromSpecies
	}
	return nil
}

func (x *Species) GetFlavorText() string {
	if x != nil {
		return x.FlavorText
	}
	return ""
}

func (x *Species) GetGenus() string {
	if x != nil {
		return x.Genus
	}
	return ""
}

func (x *Species) GetShape() *Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

type Pokemon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDefault      bool       `protobuf:"varint,3,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Number         int32      `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Types          []*Type    `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
	Description    string     `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Moves          []*Move    `protobuf:"bytes,7,rep,name=moves,proto3" json:"moves,omitempty"`
	Abilities      []*Ability `protobuf:"bytes,8,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Stats          []*Stat    `protobuf:"bytes,9,rep,name=stats,proto3" json:"stats,omitempty"`
	Height         int32      `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	Weight         int32      `protobuf:"varint,11,opt,name=weight,proto3" json:"weight,omitempty"`
	BaseExperience int32      `protobuf:"varint,12,opt,name=baseExperience,proto3" json:"baseExperience,omitempty"`
	Order          int32      `protobuf:"varint,13,opt,name=order,proto3" json:"order,omitempty"`
	Sprites        *Sprite    `protobuf:"bytes,14,opt,name=sprites,proto3" json:"sprites,omitempty"`
	Species        *Species   `protobuf:"bytes,15,opt,name=species,proto3" json:"species,omitempty"`
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{11}
}

func (x *Pokemon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pokemon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pokemon) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Pokemon) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Pokemon) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Pokemon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pokemon) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *Pokemon) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *Pokemon) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Pokemon) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Pokemon) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Pokemon) GetBaseExperience() int32 {
	if x != nil {
		return x.BaseExperience
	}
	return 0
}

func (x *Pokemon) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Pokemon) GetSprites() *Sprite {
	if x != nil {
		return x.Sprites
	}
	return nil
}

func (x *Pokemon) GetSpecies() *Species {
	if x != nil {
		return x.Species
	}
	return nil
}

type PokemonSimple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Types []*Type `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *PokemonSimple) Reset() {
	*x = PokemonSimple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonSimple) ProtoMessage() {}

func (x *PokemonSimple) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonSimple.ProtoReflect.Descriptor instead.
func (*PokemonSimple) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{12}
}

func (x *PokemonSimple) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PokemonSimple) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PokemonSimple) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type PokemonList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon []*PokemonSimple `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
}

func (x *PokemonList) Reset() {
	*x = PokemonList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonList) ProtoMessage() {}

func (x *PokemonList) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonList.ProtoReflect.Descriptor instead.
func (*PokemonList) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{13}
}

func (x *PokemonList) GetPokemon() []*PokemonSimple {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

type GetPokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetPokemonRequest) Reset() {
	*x = GetPokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonRequest) ProtoMessage() {}

func (x *GetPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonRequest) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{14}
}

func (x *GetPokemonRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetPokemonByTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *GetPokemonByTypeRequest) Reset() {
	*x = GetPokemonByTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonByTypeRequest) ProtoMessage() {}

func (x *GetPokemonByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonByTypeRequest) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{15}
}

func (x *GetPokemonByTypeRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type DeletePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePokemonRequest) Reset() {
	*x = DeletePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePokemonRequest) ProtoMessage() {}

func (x *DeletePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePokemonRequest.ProtoReflect.Descriptor instead.
func (*DeletePokemonRequest) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePokemonRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddPokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number      int32  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddPokemonRequest) Reset() {
	*x = AddPokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pokemon_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPokemonRequest) ProtoMessage() {}

func (x *AddPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPokemonRequest.ProtoReflect.Descriptor instead.
func (*AddPokemonRequest) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{17}
}

func (x *AddPokemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPokemonRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *AddPokemonRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddPokemonRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_pokemon_proto protoreflect.FileDescriptor

var file_pokemon_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x4e, 0x0a, 0x13, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x13, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x22, 0x89, 0x01, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6d,
	0x6f, 0x76, 0x65, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x6f, 0x76, 0x65, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4d, 0x0a,
	0x07, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x22, 0x4e, 0x0a, 0x04,
	0x53, 0x74, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x66, 0x66, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x22, 0x3e, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0xa4, 0x02, 0x0a,
	0x06, 0x53, 0x70, 0x72, 0x69, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x61, 0x63, 0x6b, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x28, 0x0a,
	0x0f, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x68, 0x69, 0x6e,
	0x79, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x53, 0x68, 0x69, 0x6e, 0x79, 0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x46, 0x65, 0x6d,
	0x61, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x2e, 0x0a, 0x08, 0x45, 0x67, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x38, 0x0a, 0x12, 0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x05, 0x53,
	0x68, 0x61, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xfe, 0x02, 0x0a, 0x07, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x48, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x62, 0x61, 0x73,
	0x65, 0x48, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x09, 0x65, 0x67, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x67, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x09, 0x65, 0x67, 0x67, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x65, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x65, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x4b, 0x0a, 0x12, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x73, 0x46, 0x72,
	0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x52, 0x12, 0x65, 0x76, 0x6f, 0x6c, 0x76,
	0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x66, 0x6c, 0x61, 0x76, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x6c, 0x61, 0x76, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x68, 0x61,
	0x70, 0x65, 0x52, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x22, 0xe9, 0x03, 0x0a, 0x07, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x29,
	0x0a, 0x07, 0x73, 0x70, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x07, 0x73, 0x70, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x52, 0x07, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x0d, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22,
	0x3f, 0x0a, 0x0b, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2f, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x26,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x96, 0x03,
	0x0a, 0x0e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x3a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1a, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x46,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12,
	0x1d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x6c, 0x33, 0x30, 0x30, 0x30, 0x2f, 0x50, 0x6f, 0x6b,
	0x65, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pokemon_proto_rawDescOnce sync.Once
	file_pokemon_proto_rawDescData = file_pokemon_proto_rawDesc
)

func file_pokemon_proto_rawDescGZIP() []byte {
	file_pokemon_proto_rawDescOnce.Do(func() {
		file_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_pokemon_proto_rawDescData)
	})
	return file_pokemon_proto_rawDescData
}

var file_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pokemon_proto_goTypes = []interface{}{
	(*Move)(nil),                    // 0: pokemon.Move
	(*VersionGroupDetails)(nil),     // 1: pokemon.VersionGroupDetails
	(*Ability)(nil),                 // 2: pokemon.Ability
	(*Stat)(nil),                    // 3: pokemon.Stat
	(*Type)(nil),                    // 4: pokemon.Type
	(*Sprite)(nil),                  // 5: pokemon.Sprite
	(*Colour)(nil),                  // 6: pokemon.Colour
	(*EggGroup)(nil),                // 7: pokemon.EggGroup
	(*EvolvesFromSpecies)(nil),      // 8: pokemon.EvolvesFromSpecies
	(*Shape)(nil),                   // 9: pokemon.Shape
	(*Species)(nil),                 // 10: pokemon.Species
	(*Pokemon)(nil),                 // 11: pokemon.Pokemon
	(*PokemonSimple)(nil),           // 12: pokemon.PokemonSimple
	(*PokemonList)(nil),             // 13: pokemon.PokemonList
	(*GetPokemonRequest)(nil),       // 14: pokemon.GetPokemonRequest
	(*GetPokemonByTypeRequest)(nil), // 15: pokemon.GetPokemonByTypeRequest
	(*DeletePokemonRequest)(nil),    // 16: pokemon.DeletePokemonRequest
	(*AddPokemonRequest)(nil),       // 17: pokemon.AddPokemonRequest
	(*emptypb.Empty)(nil),           // 18: google.protobuf.Empty
}
var file_pokemon_proto_depIdxs = []int32{
	1,  // 0: pokemon.Move.versionGroupDetails:type_name -> pokemon.VersionGroupDetails
	6,  // 1: pokemon.Species.color:type_name -> pokemon.Colour
	7,  // 2: pokemon.Species.eggGroups:type_name -> pokemon.EggGroup
	8,  // 3: pokemon.Species.evolvesFromSpecies:type_name -> pokemon.EvolvesFromSpecies
	9,  // 4: pokemon.Species.shape:type_name -> pokemon.Shape
	4,  // 5: pokemon.Pokemon.types:type_name -> pokemon.Type
	0,  // 6: pokemon.Pokemon.moves:type_name -> pokemon.Move
	2,  // 7: pokemon.Pokemon.abilities:type_name -> pokemon.Ability
	3,  // 8: pokemon.Pokemon.stats:type_name -> pokemon.Stat
	5,  // 9: pokemon.Pokemon.sprites:type_name -> pokemon.Sprite
	10, // 10: pokemon.Pokemon.species:type_name -> pokemon.Species
	4,  // 11: pokemon.PokemonSimple.types:type_name -> pokemon.Type
	12, // 12: pokemon.PokemonList.pokemon:type_name -> pokemon.PokemonSimple
	18, // 13: pokemon.PokemonService.GetAllPokemon:input_type -> google.protobuf.Empty
	14, // 14: pokemon.PokemonService.GetPokemon:input_type -> pokemon.GetPokemonRequest
	15, // 15: pokemon.PokemonService.GetPokemonByType:input_type -> pokemon.GetPokemonByTypeRequest
	17, // 16: pokemon.PokemonService.AddPokemon:input_type -> pokemon.AddPokemonRequest
	11, // 17: pokemon.PokemonService.UpdatePokemon:input_type -> pokemon.Pokemon
	16, // 18: pokemon.PokemonService.DeletePokemon:input_type -> pokemon.DeletePokemonRequest
	13, // 19: pokemon.PokemonService.GetAllPokemon:output_type -> pokemon.PokemonList
	11, // 20: pokemon.PokemonService.GetPokemon:output_type -> pokemon.Pokemon
	13, // 21: pokemon.PokemonService.GetPokemonByType:output_type -> pokemon.PokemonList
	11, // 22: pokemon.PokemonService.AddPokemon:output_type -> pokemon.Pokemon
	18, // 23: pokemon.PokemonService.UpdatePokemon:output_type -> google.protobuf.Empty
	18, // 24: pokemon.PokemonService.DeletePokemon:output_type -> google.protobuf.Empty
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pokemon_proto_init() }
func file_pokemon_proto_init() {
	if File_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pokemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionGroupDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sprite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Colour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EggGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvolvesFromSpecies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shape); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Species); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pokemon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonSimple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonByTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pokemon_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pokemon_proto_goTypes,
		DependencyIndexes: file_pokemon_proto_depIdxs,
		MessageInfos:      file_pokemon_proto_msgTypes,
	}.Build()
	File_pokemon_proto = out.File
	file_pokemon_proto_rawDesc = nil
	file_pokemon_proto_goTypes = nil
	file_pokemon_proto_depIdxs = nil
}
